# *******************************************************************************
# Copyright (c) 2026 Accenture
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_test(
    name = "bsp_output_pwm_test",
    srcs = ["src/IncludeTest.cpp"],
    target_compatible_with = ["//bazel/platform/constraints/build_variant:unit_test"],
    deps = [
        "//libs/3rdparty/googletest:gtest_main",
        "//libs/bsp/bspOutputPwm:bsp_output_pwm_headers",
        "//libs/bsw/util:util_mock",
    ],
)
