Setup the test enviroment
  $ . ${TESTDIR}/../../test/setup.sh
   RefApp: LIFECYCLE: DEBUG: Run level 9 done\r (esc)

  $ advance_output serial
  $ advance_output can

Send a CAN frame to the echo service in the referenceApp
  $ cansend vcan0 "123#AABBCCDDEEFF"

Check that we see the message being sent on the bus
  $ wait_output can 'vcan0  123'
    vcan0  123   [6]  AA BB CC DD EE FF

  $ sleep 10

Check that we see notification about the reception of the message on the serial out
  $ wait_output serial 'received CAN frame, id=0x123, length=6'
   RefApp: CAN: DEBUG: [SocketCanTransceiver] received CAN frame, id=0x123, length=6\r (esc)

Check that we the the echo response on the bus
  $ wait_output can 'vcan0  124'
    vcan0  124   [6]  AA BB CC DD EE FF

  $ send_serial "can send 0x100 1 2 3 4 5 6 7 8"
  $ wait_output can 'vcan0  100'
    vcan0  100   [8]  01 02 03 04 05 06 07 08

  $ ping -c 2 -W 2 192.168.0.201
  PING 192.168.0.201 (192.168.0.201) 56(84) bytes of data.
  64 bytes from 192.168.0.201: icmp_seq=1 ttl=255 time=* ms (glob)
  64 bytes from 192.168.0.201: icmp_seq=2 ttl=255 time=* ms (glob)
  
  --- 192.168.0.201 ping statistics ---
  2 packets transmitted, 2 received, 0% packet loss, time 1002ms
  rtt min/avg/max/mdev = */*/*/* ms (glob)

  $ advance_output serial
  $ send_serial "lc reboot"
  $ wait_output serial 'Lifecycle shutdown complete'
   RefApp: LIFECYCLE: INFO: Lifecycle shutdown complete\r (esc)

  $ cat "${TESTTMP}/serial.out"
  hello\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize level 1\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize runtime\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize safety\r (esc)
   RefApp: SAFETY: DEBUG: SafetyManager initialized\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize safety done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize runtime done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize level 1 done\r (esc)
   RefApp: LIFECYCLE: INFO: Run level 1\r (esc)
   RefApp: LIFECYCLE: INFO: Run runtime\r (esc)
   RefApp: LIFECYCLE: INFO: Run safety\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run safety done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run runtime done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run level 1 done\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize level 2\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize can\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize eth\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize eth done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize can done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize level 2 done\r (esc)
   RefApp: LIFECYCLE: INFO: Run level 2\r (esc)
   RefApp: LIFECYCLE: INFO: Run can\r (esc)
   RefApp: LIFECYCLE: INFO: Run eth\r (esc)
   RefApp: ETHERNET: INFO: TapEthernetDriver started!\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run eth done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run can done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run level 2 done\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize level 3\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize level 3 done\r (esc)
   RefApp: LIFECYCLE: INFO: Run level 3\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run level 3 done\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize level 4\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize transport\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize transport done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize level 4 done\r (esc)
   RefApp: LIFECYCLE: INFO: Run level 4\r (esc)
   RefApp: LIFECYCLE: INFO: Run transport\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run transport done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run level 4 done\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize level 5\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize docan\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize ethernet\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize storage\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize docan done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize ethernet done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize storage done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize level 5 done\r (esc)
   RefApp: LIFECYCLE: INFO: Run level 5\r (esc)
   RefApp: LIFECYCLE: INFO: Run docan\r (esc)
   RefApp: LIFECYCLE: INFO: Run ethernet\r (esc)
   RefApp: LIFECYCLE: INFO: Run storage\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run docan done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run ethernet done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run storage done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run level 5 done\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize level 6\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize doipServer\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize doipServer done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize level 6 done\r (esc)
   RefApp: LIFECYCLE: INFO: Run level 6\r (esc)
   RefApp: LIFECYCLE: INFO: Run doipServer\r (esc)
   RefApp: TCP: INFO: Socket prepared at port 13400\r (esc)
   RefApp: DOIP: INFO: DoIp Initialized\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run doipServer done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run level 6 done\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize level 7\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize uds\r (esc)
   RefApp: UDP: INFO: DatagramSocket bound to UDP port 13400\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize uds done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize level 7 done\r (esc)
   RefApp: LIFECYCLE: INFO: Run level 7\r (esc)
   RefApp: LIFECYCLE: INFO: Run uds\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run uds done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run level 7 done\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize level 8\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize sysadmin\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize sysadmin done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize level 8 done\r (esc)
   RefApp: LIFECYCLE: INFO: Run level 8\r (esc)
   RefApp: LIFECYCLE: INFO: Run sysadmin\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run sysadmin done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run level 8 done\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize level 9\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize demo\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize demo done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize level 9 done\r (esc)
   RefApp: LIFECYCLE: INFO: Run level 9\r (esc)
   RefApp: LIFECYCLE: INFO: Run demo\r (esc)
   RefApp: UDP: INFO: UDP echo test server initialisation\r (esc)
   RefApp: UDP: INFO: DatagramSocket bound to UDP port 49444\r (esc)
   RefApp: UDP: INFO: Listening on port 49444.\r (esc)
   RefApp: UDP: INFO: DatagramSocket joined the group\r (esc)
   RefApp: UDP: INFO: Joined multicast group\r (esc)
   RefApp: UDP: INFO: UDP Iperf2 server initialisation\r (esc)
   RefApp: UDP: INFO: DatagramSocket bound to UDP port 5001\r (esc)
   RefApp: UDP: INFO: Listening on port 5001.\r (esc)
   RefApp: TCP: INFO: Socket prepared at port 49555\r (esc)
   RefApp: TCP: INFO: Socket prepared at port 5001\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run demo done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run level 9 done\r (esc)
   RefApp: ETHERNET: INFO: linkStatusChanged(UP)\r (esc)
   RefApp: ETHERNET: INFO: linkStatusChanged(UP)\r (esc)
   RefApp: DEMO: DEBUG: Storage read done, result=3, size=5, charParam0=0x9\r (esc)
   RefApp: DEMO: DEBUG: Storage write done, result=3\r (esc)
   RefApp: DEMO: DEBUG: Sending frame 0\r (esc)
   RefApp: CAN: DEBUG: [CanDemoListener] CAN frame sent, id=0x558, length=4\r (esc)
   RefApp: CAN: DEBUG: [SocketCanTransceiver] received CAN frame, id=0x123, length=6\r (esc)
   RefApp: CAN: DEBUG: [CanDemoListener] received CAN frame, id=0x123, length=6\r (esc)
   RefApp: CAN: DEBUG: [CanDemoListener] response queued, result = 0\r (esc)
   RefApp: CAN: DEBUG: [CanDemoListener] CAN frame sent, id=0x124, length=6\r (esc)
   RefApp: DEMO: DEBUG: Sending frame 1\r (esc)
   RefApp: CAN: DEBUG: [CanDemoListener] CAN frame sent, id=0x558, length=4\r (esc)
   RefApp: DEMO: DEBUG: Sending frame 2\r (esc)
   RefApp: CAN: DEBUG: [CanDemoListener] CAN frame sent, id=0x558, length=4\r (esc)
   RefApp: DEMO: DEBUG: Sending frame 3\r (esc)
   RefApp: CAN: DEBUG: [CanDemoListener] CAN frame sent, id=0x558, length=4\r (esc)
   RefApp: DEMO: DEBUG: Sending frame 4\r (esc)
   RefApp: CAN: DEBUG: [CanDemoListener] CAN frame sent, id=0x558, length=4\r (esc)
   RefApp: DEMO: DEBUG: Sending frame 5\r (esc)
   RefApp: CAN: DEBUG: [CanDemoListener] CAN frame sent, id=0x558, length=4\r (esc)
   RefApp: DEMO: DEBUG: Sending frame 6\r (esc)
   RefApp: CAN: DEBUG: [CanDemoListener] CAN frame sent, id=0x558, length=4\r (esc)
   RefApp: DEMO: DEBUG: Sending frame 7\r (esc)
   RefApp: CAN: DEBUG: [CanDemoListener] CAN frame sent, id=0x558, length=4\r (esc)
   RefApp: DEMO: DEBUG: Sending frame 8\r (esc)
   RefApp: CAN: DEBUG: [CanDemoListener] CAN frame sent, id=0x558, length=4\r (esc)
   RefApp: DEMO: DEBUG: Sending frame 9\r (esc)
   RefApp: CAN: DEBUG: [CanDemoListener] CAN frame sent, id=0x558, length=4\r (esc)
   RefApp: DEMO: DEBUG: Sending frame 10\r (esc)
   RefApp: CAN: DEBUG: [CanDemoListener] CAN frame sent, id=0x558, length=4\r (esc)
   RefApp: DEMO: DEBUG: Sending frame 11\r (esc)
   RefApp: CAN: DEBUG: [CanDemoListener] CAN frame sent, id=0x558, length=4\r (esc)
   RefApp: DEMO: DEBUG: Sending frame 12\r (esc)
   RefApp: CAN: DEBUG: [CanDemoListener] CAN frame sent, id=0x558, length=4\r (esc)
   RefApp: DEMO: DEBUG: Sending frame 13\r (esc)
   RefApp: CAN: DEBUG: [CanDemoListener] CAN frame sent, id=0x558, length=4\r (esc)
  can send 0x100 1 2 3 4 5 6 7 8\r (esc)
   ok\r (esc)
  \r (esc)
   RefApp: CONSOLE: INFO: Received console command "can send 0x100 1 2 3 4 5 6 7 8"\r (esc)
   RefApp: CONSOLE: INFO: Console command succeeded\r (esc)
   RefApp: CAN: DEBUG: [CanDemoListener] CAN frame sent, id=0x100, length=8\r (esc)
   RefApp: DEMO: DEBUG: Sending frame 14\r (esc)
   RefApp: CAN: DEBUG: [CanDemoListener] CAN frame sent, id=0x558, length=4\r (esc)
   RefApp: DEMO: DEBUG: Sending frame 15\r (esc)
   RefApp: CAN: DEBUG: [CanDemoListener] CAN frame sent, id=0x558, length=4\r (esc)
   RefApp: DEMO: DEBUG: Sending frame 16\r (esc)
   RefApp: CAN: DEBUG: [CanDemoListener] CAN frame sent, id=0x558, length=4\r (esc)
   RefApp: DEMO: DEBUG: Sending frame 17\r (esc)
   RefApp: CAN: DEBUG: [CanDemoListener] CAN frame sent, id=0x558, length=4\r (esc)
  lc reboot\r (esc)
   ok\r (esc)
  \r (esc)
   RefApp: CONSOLE: INFO: Received console command "lc reboot"\r (esc)
   RefApp: CONSOLE: INFO: Console command succeeded\r (esc)
   RefApp: LIFECYCLE: INFO: Shutdown level 9\r (esc)
   RefApp: LIFECYCLE: INFO: Shutdown demo\r (esc)
   RefApp: UDP: INFO: Closing port 49444.\r (esc)
   RefApp: UDP: INFO: DatagramSocket @ port 49444 closed\r (esc)
   RefApp: UDP: INFO: Closing port 5001.\r (esc)
   RefApp: UDP: INFO: DatagramSocket @ port 5001 closed\r (esc)
   RefApp: TCP: INFO: Socket at port 49555 closed\r (esc)
   RefApp: TCP: INFO: Socket at port 5001 closed\r (esc)
   RefApp: LIFECYCLE: DEBUG: Shutdown demo done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Shutdown level 9 done\r (esc)
   RefApp: LIFECYCLE: INFO: Shutdown level 8\r (esc)
   RefApp: LIFECYCLE: INFO: Shutdown sysadmin\r (esc)
   RefApp: LIFECYCLE: DEBUG: Shutdown sysadmin done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Shutdown level 8 done\r (esc)
   RefApp: LIFECYCLE: INFO: Shutdown level 7\r (esc)
   RefApp: LIFECYCLE: INFO: Shutdown uds\r (esc)
   RefApp: UDS: DEBUG: DiagDispatcher::shutdown()\r (esc)
   RefApp: UDS: DEBUG: DiagDispatcher incoming connection shutdown complete\r (esc)
   RefApp: UDS: DEBUG: DiagDispatcher::connectionManagerShutdownComplete()\r (esc)
   RefApp: LIFECYCLE: DEBUG: Shutdown uds done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Shutdown level 7 done\r (esc)
   RefApp: LIFECYCLE: INFO: Shutdown level 6\r (esc)
   RefApp: LIFECYCLE: INFO: Shutdown doipServer\r (esc)
   RefApp: TCP: INFO: Socket at port 13400 closed\r (esc)
   RefApp: DOIP: DEBUG: DoIpServerTransportLayer::closeAllConnections()\r (esc)
   RefApp: LIFECYCLE: DEBUG: Shutdown doipServer done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Shutdown level 6 done\r (esc)
   RefApp: LIFECYCLE: INFO: Shutdown level 5\r (esc)
   RefApp: LIFECYCLE: INFO: Shutdown docan\r (esc)
   RefApp: LIFECYCLE: INFO: Shutdown ethernet\r (esc)
   RefApp: LIFECYCLE: INFO: Shutdown storage\r (esc)
   RefApp: LIFECYCLE: DEBUG: Shutdown docan done\r (esc)
   RefApp: DOIP: DEBUG: DoIpServerTransportLayer::executeEventClose()\r (esc)
   RefApp: UDP: INFO: DatagramSocket @ port 13400 closed\r (esc)
   RefApp: LIFECYCLE: DEBUG: Shutdown ethernet done\r (esc)
   RefApp: DOIP: DEBUG: DoIpServerTransportLayer::releaseConnections()\r (esc)
   RefApp: LIFECYCLE: DEBUG: Shutdown storage done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Shutdown level 5 done\r (esc)
   RefApp: LIFECYCLE: INFO: Shutdown level 4\r (esc)
   RefApp: LIFECYCLE: INFO: Shutdown transport\r (esc)
   RefApp: LIFECYCLE: DEBUG: Shutdown transport done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Shutdown level 4 done\r (esc)
   RefApp: LIFECYCLE: INFO: Shutdown level 3\r (esc)
   RefApp: LIFECYCLE: DEBUG: Shutdown level 3 done\r (esc)
   RefApp: LIFECYCLE: INFO: Shutdown level 2\r (esc)
   RefApp: LIFECYCLE: INFO: Shutdown can\r (esc)
   RefApp: LIFECYCLE: INFO: Shutdown eth\r (esc)
   RefApp: LIFECYCLE: DEBUG: Shutdown eth done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Shutdown can done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Shutdown level 2 done\r (esc)
   RefApp: LIFECYCLE: INFO: Shutdown level 1\r (esc)
   RefApp: LIFECYCLE: INFO: Shutdown runtime\r (esc)
   RefApp: LIFECYCLE: INFO: Shutdown safety\r (esc)
   RefApp: LIFECYCLE: DEBUG: Shutdown safety done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Shutdown runtime done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Shutdown level 1 done\r (esc)
   RefApp: LIFECYCLE: INFO: Lifecycle shutdown complete\r (esc)
  hello\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize level 1\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize runtime\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize safety\r (esc)
   RefApp: SAFETY: DEBUG: SafetyManager initialized\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize safety done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize runtime done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize level 1 done\r (esc)
   RefApp: LIFECYCLE: INFO: Run level 1\r (esc)
   RefApp: LIFECYCLE: INFO: Run runtime\r (esc)
   RefApp: LIFECYCLE: INFO: Run safety\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run safety done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run runtime done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run level 1 done\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize level 2\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize can\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize eth\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize eth done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize can done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize level 2 done\r (esc)
   RefApp: LIFECYCLE: INFO: Run level 2\r (esc)
   RefApp: LIFECYCLE: INFO: Run can\r (esc)
   RefApp: LIFECYCLE: INFO: Run eth\r (esc)
   RefApp: ETHERNET: INFO: TapEthernetDriver started!\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run eth done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run can done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run level 2 done\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize level 3\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize level 3 done\r (esc)
   RefApp: LIFECYCLE: INFO: Run level 3\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run level 3 done\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize level 4\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize transport\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize transport done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize level 4 done\r (esc)
   RefApp: LIFECYCLE: INFO: Run level 4\r (esc)
   RefApp: LIFECYCLE: INFO: Run transport\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run transport done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run level 4 done\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize level 5\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize docan\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize ethernet\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize storage\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize docan done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize ethernet done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize storage done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize level 5 done\r (esc)
   RefApp: LIFECYCLE: INFO: Run level 5\r (esc)
   RefApp: LIFECYCLE: INFO: Run docan\r (esc)
   RefApp: LIFECYCLE: INFO: Run ethernet\r (esc)
   RefApp: LIFECYCLE: INFO: Run storage\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run docan done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run ethernet done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run storage done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run level 5 done\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize level 6\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize doipServer\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize doipServer done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize level 6 done\r (esc)
   RefApp: LIFECYCLE: INFO: Run level 6\r (esc)
   RefApp: LIFECYCLE: INFO: Run doipServer\r (esc)
   RefApp: TCP: INFO: Socket prepared at port 13400\r (esc)
   RefApp: DOIP: INFO: DoIp Initialized\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run doipServer done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run level 6 done\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize level 7\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize uds\r (esc)
   RefApp: UDP: INFO: DatagramSocket bound to UDP port 13400\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize uds done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize level 7 done\r (esc)
   RefApp: LIFECYCLE: INFO: Run level 7\r (esc)
   RefApp: LIFECYCLE: INFO: Run uds\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run uds done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run level 7 done\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize level 8\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize sysadmin\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize sysadmin done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize level 8 done\r (esc)
   RefApp: LIFECYCLE: INFO: Run level 8\r (esc)
   RefApp: LIFECYCLE: INFO: Run sysadmin\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run sysadmin done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run level 8 done\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize level 9\r (esc)
   RefApp: LIFECYCLE: INFO: Initialize demo\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize demo done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Initialize level 9 done\r (esc)
   RefApp: LIFECYCLE: INFO: Run level 9\r (esc)
   RefApp: LIFECYCLE: INFO: Run demo\r (esc)
   RefApp: UDP: INFO: UDP echo test server initialisation\r (esc)
   RefApp: UDP: INFO: DatagramSocket bound to UDP port 49444\r (esc)
   RefApp: UDP: INFO: Listening on port 49444.\r (esc)
   RefApp: UDP: INFO: DatagramSocket joined the group\r (esc)
   RefApp: UDP: INFO: Joined multicast group\r (esc)
   RefApp: UDP: INFO: UDP Iperf2 server initialisation\r (esc)
   RefApp: UDP: INFO: DatagramSocket bound to UDP port 5001\r (esc)
   RefApp: UDP: INFO: Listening on port 5001.\r (esc)
   RefApp: TCP: INFO: Socket prepared at port 49555\r (esc)
   RefApp: TCP: INFO: Socket prepared at port 5001\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run demo done\r (esc)
   RefApp: LIFECYCLE: DEBUG: Run level 9 done\r (esc)
   RefApp: ETHERNET: INFO: linkStatusChanged(UP)\r (esc)
   RefApp: ETHERNET: INFO: linkStatusChanged(UP)\r (esc)
   RefApp: DEMO: DEBUG: Storage read done, result=3, size=5, charParam0=0xA\r (esc)
   RefApp: DEMO: DEBUG: Storage write done, result=3\r (esc)
   RefApp: DEMO: DEBUG: Sending frame 0\r (esc)
   RefApp: CAN: DEBUG: [CanDemoListener] CAN frame sent, id=0x558, length=4\r (esc)
  $ cat "${TESTTMP}/can.out"
    vcan0  558   [4]  00 00 00 00
    vcan0  123   [6]  AA BB CC DD EE FF
    vcan0  124   [6]  AA BB CC DD EE FF
    vcan0  558   [4]  00 00 00 01
    vcan0  558   [4]  00 00 00 02
    vcan0  558   [4]  00 00 00 03
    vcan0  558   [4]  00 00 00 04
    vcan0  558   [4]  00 00 00 05
    vcan0  558   [4]  00 00 00 06
    vcan0  558   [4]  00 00 00 07
    vcan0  558   [4]  00 00 00 08
    vcan0  558   [4]  00 00 00 09
    vcan0  558   [4]  00 00 00 0A
    vcan0  558   [4]  00 00 00 0B
    vcan0  558   [4]  00 00 00 0C
    vcan0  558   [4]  00 00 00 0D
    vcan0  100   [8]  01 02 03 04 05 06 07 08
    vcan0  558   [4]  00 00 00 0E
    vcan0  558   [4]  00 00 00 0F
    vcan0  558   [4]  00 00 00 10
    vcan0  558   [4]  00 00 00 11
    vcan0  558   [4]  00 00 00 00
