if(EXISTS "/home/jenkins/code_coverage/libs/bsw/runtime/test/gtest/runtimeTest[1]_tests.cmake")
  include("/home/jenkins/code_coverage/libs/bsw/runtime/test/gtest/runtimeTest[1]_tests.cmake")
else()
  add_test(runtimeTest_NOT_BUILT runtimeTest_NOT_BUILT)
endif()
