# *******************************************************************************
# Copyright (c) 2026 Accenture
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# C headers generated from Rust FFI with cbindgen. cbindgen is deliberately not a
# build dependency (its dependency tree would bloat the vendored crates), so the
# headers are checked-in artifacts regenerated by this script. Add an entry here
# for every crate that ships a generated header.
CBINDGEN_HEADERS = [
    {
        "crate_dir": "libs/bsw/logger/rust",
        "crate": "openbsw-logger",
        "output": "libs/bsw/logger/rust/include/BswLogger.h",
    },
]


def regenerate_headers():
    for header in CBINDGEN_HEADERS:
        crate_dir = REPO_ROOT / header["crate_dir"]
        subprocess.run(
            [
                "cbindgen",
                "--config", str(crate_dir / "cbindgen.toml"),
                "--crate", header["crate"],
                "--output", str(REPO_ROOT / header["output"]),
                str(crate_dir),
            ],
            check=True,
        )
    # Fail if a committed header was out of date with the current FFI.
    subprocess.run(["git", "diff", "--exit-code"], check=True, cwd=REPO_ROOT)


if __name__ == "__main__":
    try:
        regenerate_headers()
    except subprocess.CalledProcessError as e:
        print(f"Command failed with exit code {e.returncode}")
        sys.exit(e.returncode)
