# CMake generated Testfile for 
# Source directory: /home/jenkins
# Build directory: /home/jenkins/code_coverage
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("platforms")
subdirs("libs")
subdirs("libs/bsw/async/test/gtest")
subdirs("libs/bsw/asyncConsole/test/gtest")
subdirs("libs/bsw/asyncFreeRtos/test/gtest")
subdirs("libs/bsw/asyncImpl/examples")
subdirs("libs/bsw/asyncImpl/test/gtest")
subdirs("libs/bsw/bsp/test/gtest")
subdirs("libs/bsw/cpp2can/test/gtest")
subdirs("libs/bsw/cpp2ethernet/test/gtest")
subdirs("libs/bsw/docan/test/gtest")
subdirs("libs/bsw/io/examples")
subdirs("libs/bsw/io/test")
subdirs("libs/bsw/lifecycle/examples")
subdirs("libs/bsw/lifecycle/test/gtest")
subdirs("libs/bsw/logger/test")
subdirs("libs/bsw/lwipSocket/test/gtest")
subdirs("libs/bsw/platform/test/gtest")
subdirs("libs/bsw/runtime/test/gtest")
subdirs("libs/bsw/storage/test/gtest")
subdirs("libs/bsw/timer/test/gtest")
subdirs("libs/bsw/transport/test/gtest")
subdirs("libs/bsw/uds/test/gtest")
subdirs("libs/bsw/util/test/gtest")
subdirs("libs/bsp/bspInputManager/test/gtest")
subdirs("libs/bsp/bspCharInputOutput/test/gtest")
subdirs("libs/bsp/bspDynamicClient/test/gtest")
subdirs("libs/bsp/bspInterrupts/test/gtest")
subdirs("libs/bsp/bspOutputManager/test/gtest")
subdirs("libs/bsp/bspOutputPwm/test/gtest")
subdirs("libs/safety/safeUtils/test/gtest")
subdirs("libs/safety/safeMonitor/test")
subdirs("platforms/posix/bsp/bspEepromDriver/test/gtest")
subdirs("platforms/posix/bsp/socketCanTransceiver")
subdirs("platforms/posix/bsp/socketCanTransceiver/test/gtest")
subdirs("platforms/s32k1xx/bsp/bspCore/test/gtest")
subdirs("platforms/s32k1xx/bsp/bspEepromDriver/test/gtest")
subdirs("platforms/s32k1xx/bsp/bspIo/test/gtest")
subdirs("platforms/s32k1xx/bsp/bspSci/test/gtest")
subdirs("platforms/s32k1xx/bsp/canflex2Transceiver")
subdirs("platforms/s32k1xx/bsp/canflex2Transceiver/test/gtest")
subdirs("platforms/s32k1xx/bsp/canflex2Transceiver/test/mock")
subdirs("executables/referenceApp/safety/safeSupervisor")
subdirs("executables/referenceApp/safety/safeSupervisor/test/gtest")
subdirs("executables/unitTest")
