/********************************************************************************
 * Copyright (c) 2026 Accenture
 *
 * This program and the accompanying materials are made available under the
 * terms of the Apache License Version 2.0 which is available at
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * SPDX-License-Identifier: Apache-2.0
 ********************************************************************************/

// clang-format off

#pragma once

/* Generated by cbindgen. Do not modify! */

#include <cstdint>
#include "util/logger/LevelInfo.h"

namespace logger {

/// Sentinel value indicating an unresolved component (matches C++ `COMPONENT_NONE`).
constexpr static const uint8_t COMPONENT_NONE = 255;

struct BswLogger;

extern "C" {

extern BswLogger LOGGER;

extern void bsw_cpp_logger_log(uint8_t component_index,
                               ::util::logger::Level level,
                               const char *str);

/// Mirror of `::util::logger::Logger::isEnabled`: returns whether the C++ logger
/// would actually emit an entry for this component/level.
extern bool bsw_cpp_logger_is_enabled(uint8_t component_index, ::util::logger::Level level);

/// Set the fallback logger component for messages routed through the `log` facade
/// (e.g. plain `log::info!(...)` calls from this crate or third-party deps).
///
/// `component_index` is the C++ `::util::logger::<NAME>` symbol (a `uint8_t`)
/// populated by the logger composition. Pass it directly rather than a name to
/// avoid an unnecessary lookup.
///
/// If this is not called, log messages routed through the `log` facade are silently
/// dropped. Rust code using the per-component `bsw_*!` macros is unaffected.
void set_default_component(uint8_t component_index);

/// The rust logger must be installed after configuration
void install_rust_logging();

}  // extern "C"

}  // namespace logger

// clang-format on
