if(EXISTS "/home/jenkins/code_coverage/platforms/s32k1xx/bsp/bspSci/test/gtest/bspSciTest[1]_tests.cmake")
  include("/home/jenkins/code_coverage/platforms/s32k1xx/bsp/bspSci/test/gtest/bspSciTest[1]_tests.cmake")
else()
  add_test(bspSciTest_NOT_BUILT bspSciTest_NOT_BUILT)
endif()
