name: Code format check

on: [ merge_group, push, pull_request ]

jobs:
  treefmt:
    runs-on: ubuntu-latest
    steps:
     - name: Build the dockerfile
       run: |
          docker build --build-arg user_id=$(id -u) -f docker/Dockerfile.dev -t dev .

     - name: Run the build.py inside the docker container
       run: |
          docker run --rm -v "$PWD:/home/jenkins" -w /home/jenkins --user $(id -u):4996 dev python3 .ci/format.py
